build: No need to set PKG_CONFIG_PATH for g-ir-scanner
I don't see any need for this and it actually breaks the build here:

GEN      LibvirtDesigner-1.0.gir
Package libvirt-gconfig-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt-gconfig-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt-gconfig-1.0' found
In file included from <stdin>:4:0:
/extra-data/checkout/gnome/libvirt-designer/libvirt-designer/libvirt-designer.h:27:45:
fatal error: libvirt-gconfig/libvirt-gconfig.h: No such file or
directory
compilation terminated.
Error while processing the source.
make[3]: *** [LibvirtDesigner-1.0.gir] Error 1